version: '3.8'
services:
  hello-world:
    image: nginxdemos/hello
    ports:
      - "80:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - hello-net
networks:
  hello-net:
    driver: overlay




